[main]
font=monospace:size=11

[colors]
alpha=0.75
background = 000000
foreground = ffffff


regular0 = 000000
bright0 = deddda
regular1 = ffffff
bright1 = ffffff
regular2 = deddda
bright2 = deddda
regular7 = aaaaaa
bright7 = ffffff 

# Amarelo e Laranja
#regular3 = ecc450
#bright3 = ecc450
#regular4 = eaa835
#bright4 = eaa835
#regular5 = EF670E
#bright5 = EF670E
#regular6 = DB5431
#bright6 = DB5431

# Azul e Roxo
#regular3 = 57A2DC
#bright3 = 57A2DC
#regular4 = 4A8BC9
#bright4 = 4A8BC9
#regular5 = BE64A5
#bright5 = BE64A5
#regular6 = A85B93
#bright6 = A85B93

# Rosa e Roxo
#regular3 = FF82CE
#bright3 =  FF82CE
#regular4 = FF5BC1
#bright4 = FF5BC1
#regular5 = 5549AB
#bright5 = 5549AB
#regular6 = 562BB8
#bright6 = 562BB8

# Amarelo e Azul
regular3 = ecc450
bright3 = ecc450
regular4 = eaa835
bright4 = eaa835
regular5 = 57A2DC
bright5 = 57A2DC
regular6 = 4A8BC9
bright6 = 4A8BC9
